unified_mode     'true'
name             'redis'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-redis'
version          '0.0.1'
